<!DOCTYPE html>
<html>
     <head>
        <meta charset="utf-8">
        <title>Derivado de "CSS básico"</title>
        <style>
            body{
                background-color:rgb(212, 167, 212);
            }
            #Tecnicas{
                background-color:rgb(211, 240, 225);
                width:525px;
                height:22px;
                background-color:rgb(206, 235, 233);
                margin:12px -6px;
                padding:23px;
                border:2px solid ;
                display:inline-block;
            }
            
            h1{
            color:rgb(15, 135, 186);
               
            }
            #Artistica{
                color:rgb(75, 140, 60);
            }
            
            
            #Aula-de-artes{
                color:rgb(58, 140, 52);
            }
            #Esta-pagina{
                color:rgb(0, 0, 0);
            }
            #Creadora{
                color:rgb(108, 106, 201);
            }
            #Objetos{
                color:rgb(255, 252, 255);
            }
            #Materiales{
                color:rgb(102, 255, 163);
            }
            
            p{
                color:rgb(255, 252, 255);
            }
            #Creadora{
                background-color:rgb(242, 211, 242);
            }
            #Esta-pagina{
                background-color:rgb(242, 211, 242);
            }
            #Ubicacion{
                background-color:rgb(211, 240, 225);
                width:523px;
                height:60px;
                background-color:rgb(206, 235, 233);
                margin:-9px -5px;
                padding:24px;
                border:2px solid ;
                display:inline-block;
            }
            }
            #Artistica{
                font-family:Arial;
            }
            #Aula-de-artes{
                font-family:Arial;
                 background-color:rgb(212, 167, 212);
                width:88%;
                height:91px;
                overflow-y:auto;
                overflow-x:hidden;
                margin:6px 6px;
               
            }
            #Creadora{
                font-size:2em;
            }
            #Tecnicas{
                font-size:2em;
            }
            #Ubicacion{
                font-size:1em;
            }
            #Semana-1{
                font-size:2em;
            }
            #Semana-2{
                font-size:2em;
            }
            #Semana-3{
                font-size:2em;
            }
            #Semana-4{
                font-size:2em;
            }
            #Semana-5{
                font-size:2em;
            }
            #Semana-6{
                font-size:2em;
            }
            #Actividad-primera-semana{
                font-size:2em;
            }
            tr{
                background-color:rgb(255, 5, 255);
            }
            a{
            text-decoration:underline;
                
            }
            a{
                letter-spacing:5px;
                
            }
            ul{
                list-style-type:none;
                margin:0;
                padding:0;
                overflow:hidden;
            }
            li{
                float:left;
            }
            li{
                display:block;
                padding:8px;
                background-color:rgb(158, 151, 219);
                background-color:rgb(240, 195, 240);
                width:19%;
                height:31px;
                margin:7px 10px;
            }
            div h2{
                background-color:rgb(225, 223, 240);
                display:block;
                padding:8px;
                overflow:hidden;
            }
            #Semanas{
                 background-color:rgb(212, 167, 212);
                width:99%;
                height:178px;
                overflow-y:auto;
                overflow-x:hidden;
                margin:-11px 7px;
                
            }
            
            button{
                background-color:rgb(214, 195, 240);
            }
            button:hover{
                background-color:rgb(191, 82, 191);
            }
            button:active{
                background-color:rgb(8, 238, 242);
            }
            
            </style>
            
        </head>
        <body>
        <header>
        
        <h1 id="Tecnicas">ARTISTICA: Tecnicas de fotografia                </h1>
        </header>
        
        <nav><div><button><h3 id="Menu"><a href="https://miplataformaeducativa.skolmi.com/course/view.php?id=1366">Menu</a></h3></button></div>
         </nav>
         
        <section>
        <h2 id="Artistica"><em><a href="#mi-web">Ecucacion artistica</a></em></h2>
        <nav>
        <ul>
            <li><a href="#Semana-1">Semana 1</a></li>
            <li><a href="#Semana-2">Semana 2</a></li>
            <li><a href="#Semana-3">Semana 3</a></li>
            <li><a href="#Semana-4">Semana 4</a></li>
            <li><a href="#Semana-5">Semana 5</a></li>
            <li><a href="#Semana-6">Semana 6</a></li>
            </ul>
        </nav><br>
        
        <img src="https://cdn.kastatic.org/third_party/javascript-khansrc/live-editor/build/images/animals/butterfly_monarch.png" alt="Una hermosa fotografia que nos muestra detalladamente una mariposa" width="500">
        <article>
        <h3><p id="Aula-de-artes"><em>Durante el aula de artes estaremos enfocados en la fotografia.Para inspirarnos trabajaremos con lecturas propuesta.El curso pretende, mediante el análisis de la imagen fotográfica desde sus inicios hasta la actualidad, lograr un método lúdico y dinámico que permita un fácil aprendizaje de la técnica fotográfica y una correcta aplicación de la misma.</em></p></h3>
        
        </article>
        <aside>
        <strong>Cosas a tener en cuenta para iniciar con el aula de artistica</strong>
        <table>
            <tr>
            <th>Materiales</th>
            <th>Objetos</th>
            <th>Lugares</th>
            </tr>
            <tr>
                <td>Camara fotografica</td>
                <td>Una persona</td>
                <td>Casa</td>
            </tr>
            <tr>
                <td>Celular con camara</td>
                <td>Animal</td>
                <td>Parque</td>
            </tr>
            <tr>
                <td>Etc...</td>
                <td>Etc...</td>
                <td>Etc...</td>
            </tr>
        </table>
        </aside>
        <article>
         <div>   
         <h2 id="Semana-1"><a href="https://artisticagabi2022.blogspot.com/2022/02/de-lo-teorico-lo-practico.html"> Semana 1</a></h2>
         </div>
         <div id="Semanas">
         <h3 id="mi-web">De lo teorico a lo practico</h3>
        <p>El participante aprendera a manejar la camara con todas sus funciones y programas disponibles, ademas de conocer y poner en practica los principios basicos de composición en fotografia.</p>
        <h3>El nivel 1 de esta mision tiene tres (3) objetivos:</h3>
        <a href="https://www.hofmann.es/blog/fotografia/cuales-son-los-tipos-de-objetivos-fotograficos/">OBJETIVOS FOTOGRAFICOS</a>
        <table> 
            <tr>
                <th>1 objetivo</th>
                <th>2 objetivo</th>
                <th>3 objetivo</th>
            </tr>
            <tr>
                <td>Llevar a la practica los concejos basicos de la             fotografia.</td>
                <td>Realizar fotografias inspiradas en el parrafo o lectura previamente escogida.</td>
                <td>Presentar las fotografias teniendo en cuenta los planos y angulos estudiados.</td>
            </tr>
            <tr>
                <td><img src="https://www.blogdelfotografo.com/wp-content/uploads/2020/10/camara-fotos-ajustes.jpg" alt="Podemos observar como la persona toma una fotografia"></td>
                <td><img src="https://images.squarespace-cdn.com/content/v1/53aadf1de4b0a0a817640cca/1559067185327-OYW6XDBRXG25DOB8W9TI/libros++de+texto" alt="Esta imagen nos muestra un libro lo cual nos quiere representar nuestro 2 objetivo"></td>
                <td><img src="https://1.bp.blogspot.com/-3jTrOioVQg8/XqcaLpwqAbI/AAAAAAAAA5E/6rBS-BY1dacO-gfKvMrzeB8WTk9CSCrMgCLcBGAsYHQ/s1600/%25C3%2581ngulos_de_la_c%25C3%25A1mara.jpg" alt="Vemos los diferentes tipos de angulos de la camara"></td>
            </tr>
        </table>
        
        
        <h3>Angulos y planos fotograficos</h3><p>En esta primera semana estaremos viendo cuales son los diferentes tipos de Angulos y Planos fotograficos</p>
       <strong>¿Que es el Angulo fotografico?</strong><p>
        Cuando hablamos de ángulo fotográfico, nos referimos a la posición en la que colocamos la cámara para capturar la imagen, estos tienen nombre y existen cinco diferentes ángulos que se pueden utilizar para hacer fotos, lo mejor de todo es que cada uno da una percepción completamente diferente al mismo objeto.</p><strong>¿Que es el Plano fotografico?</strong><p>El plano refiere la proporción que tiene el objeto o personaje dentro del encuadre,, estos nos indican que sección de la imagen aparecerá en la toma y cuáles son los mejores cortes que se pueden realizar sin que se descuide la proporción adecuada y que la misma conserve la estética de la imagen.</P>
        </div>
        </article>
        <article>
        <h1 id="Actividad-primera-semana"><a href="https://artisticagabi2022.blogspot.com/2022/02/de-lo-teorico-lo-practico.html">Actividad primera semana</a></h1><p>En el link que encuentras justo arriba encontraras las fotografias de la actividad de la primera semana,inspiradas en un párrafo o lectura visualizadas en la temática de la semana.</p>
    
         </article>
         
         <div>
         <article>
             <h2 id="Semana-2"><a href="https://artisticagabi2022.blogspot.com/2022/02/de-lo-teorico-lo-practico.html">Semana 2</a></h2>
         </article>
         <article>
             <h2 id="Semana-3"><a href="https://artisticagabi2022.blogspot.com/2022/02/de-lo-teorico-lo-practico.html">Semana 3</a></h2>
         </article>
         <article>
             <h2 id="Semana-4"><a href="https://artisticagabi2022.blogspot.com/2022/02/de-lo-teorico-lo-practico.html">Semana 4</a></h2>
         </article>
         <article>
             <h2 id="Semana-5"><a href="https://artisticagabi2022.blogspot.com/2022/02/de-lo-teorico-lo-practico.html">Semana 5</a></h2>
         </article>
         <article>
             <h2 id="Semana-6"><a href="https://artisticagabi2022.blogspot.com/2022/02/de-lo-teorico-lo-practico.html"> Semana 6</a></h2>
         </article>
        </div>
        </section>
        <div>
        <aside>
        
        <h2 id="Creadora">Creadora</h2><h4><p id="Esta-pagina">Esta pagina web es creada por Gabriela Castro Saenz.<br>
        Puedes ecribirme un correo a <a href="mailto:gabrielacastrosaenz.2013@gmail.com">gabrielacastrosaenz.2013@gmail.com</a></p></h4>
        
        </aside>
        </div>
        <div>
        <footer id="Ubicacion">UBICACION<br>gabrielacastrosaenz.2013@gmail.com<br>Bogota-Colombia.<br>ALREDEDOR DE LA PAGINA
         </footer>
        </div>
         


    </body>
</html>
